language: go
sudo: false
arch:
  - amd64
  - ppc64le
env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go vet ./...
  - go test -v ./...
